version: '3.5'
services:
  api: # API
    build: .
    hostname: api
    depends_on:
      - db
    ports:
      - "8080:8080"
  db: # Banco de dados
    hostname: db
    image: postgres
    command: postgres -c log_min_messages=FATAL
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: livros-db
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql postgres